# Generated by Django 3.1.1 on 2020-10-02 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_crates_name_application_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="nameapplication",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Aprovado"),
        ),
        migrations.AddField(
            model_name="nameapplication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
        migrations.AddField(
            model_name="nameapplication",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Comentários"),
        ),
        migrations.AddIndex(
            model_name="nameapplication",
            index=models.Index(
                fields=["approved"], name="core_nameap_approve_6f8295_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nameapplication",
            index=models.Index(
                fields=["approved_by"], name="core_nameap_approve_dc8387_idx"
            ),
        ),
    ]
