# Generated by Django 3.1.2 on 2020-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_adds_approval_fields_to_name_application_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nameapplication",
            name="dob",
            field=models.DateField(verbose_name="Data de nascimento (dd/mm/aaaa)"),
        ),
    ]
