# Generated by Django 3.1.2 on 2020-10-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sort_proxy_user_by_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="nameapplication",
            name="status",
            field=models.CharField(
                choices=[("P", "Pendente"), ("A", "Aprovado"), ("R", "Rejeitado")],
                default="P",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="nameapplication",
            index=models.Index(fields=["status"], name="core_nameap_status_3b09ef_idx"),
        ),
    ]
