# Generated by Django 3.1.2 on 2020-10-15 23:37

from django.db import migrations


def forward(apps, schema_editor):
    NameApplication = apps.get_model("core", "NameApplication")
    for obj in NameApplication.objects.all():
        status = "A" if obj.approved else "P"
        obj.status = status
        obj.save()


def backward(apps, schema_editor):
    NameApplication = apps.get_model("core", "NameApplication")
    for obj in NameApplication.objects.all():
        obj.approved = obj.status == "A"
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_status_to_name_application_model"),
    ]

    operations = [migrations.RunPython(forward, backward)]
