name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.9
          poetry_version: 1.1.1
          args: install
      - name: Collect static files
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.9
          poetry_version: 1.1.1
          args: run python manage.py collectstatic --no-input
        env:
          SECRET_KEY: my-secret
          DATABASE_URL: "sqlite:///:memory:"
      - name: Run tests
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.9
          poetry_version: 1.1.1
          args: run pytest
        env:
          SECRET_KEY: my-secret
          DATABASE_URL: "sqlite:///:memory:"
